### ISSUE TITLE
Unresolved dependency: de.johoop#sbt-testng-interface_2.12;3.0.2: not found

### ISSUE THREAD

**Issue by oxbowlakes** [sbt/sbt-testng#14]
This is almost identical to an issue raised 2 years ago about the lack of a 2.11 interface. Note that we do have 

    resolvers += Resolver.sbtPluginRepo("releases") 

in our build file. But I can't see that a 2.12 interface has yet been published here https://dl.bintray.com/sbt/sbt-plugin-releases/de.johoop/

**Comment by jmhofer** [comment]
I've published sbt-testng-interface for Scala 2.12 now. The plugin itself should be available from the sbt plugins repo, soon, too. - As soon as it is, please check if this is working for you now (as I'm not using this myself anymore).

**Comment by jmhofer** [comment]
just to clarify: I published a version 3.0.3 for Scala 2.12 (not 3.0.2).

**Comment by oxbowlakes** [comment]
Thanks!

**Comment by jmhofer** [comment]
It should be published now in the official sbt repo.
