### ISSUE TITLE
Unresolved dependency: de.johoop#sbt-testng-interface_2.11;3.0.2: not found

### ISSUE THREAD

**Issue by soc** [sbt/sbt-testng#9]
When trying to use this plugin, I receive the following error message:

```
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: de.johoop#sbt-testng-interface_2.11;3.0.2: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
```

Any ideas how to address this?

(SBT 0.13.9, Scala 2.11.7)

**Comment by anilgursel** [comment]
https://github.com/sbt/sbt-testng-interface/pull/8/files should address this.

As a temporary workaround, you can add `resolvers += Resolver.sbtPluginRepo("releases")` in your build file.

**Comment by soc** [comment]
Thanks!

**Comment by benmccann** [comment]
I do see it published:

    https://dl.bintray.com/sbt/sbt-plugin-releases/de.johoop/sbt-testng-interface_2.11/3.0.2/

**Comment by SethTisue** [comment]
#8 was merged, so should this ticket be closed?
